/**
 * Token handling for roster authentication.
 *
 * A twin authenticates with a bearer token. Tokens are generated by the server
 * (`roster-server add-twin`) as a signed string. The server stores only a hash,
 * never the plaintext, and derives a writable secret that identifies one twin.
 *
 * Token format (server-side HMAC): `roster.<twinId>.<kind>.<sig>` where `sig` is
 * an HMAC-SHA256 over `<twinId>.<kind>` using the server secret. A "read" token
 * is scoped to reading; a "write" token is scoped to a single twin and to
 * writing that twin. A shared "read-all" token may use twinId `*`.
 *
 * @module @roster/core
 */

import { createHmac, randomBytes, timingSafeEqual } from 'node:crypto'

export const TOKEN_PREFIX = 'roster.'

export type TokenKind = 'read' | 'write'

export interface TokenPayload {
  twinId: string
  kind: TokenKind
}

const HEADER = Buffer.from('rstr1', 'utf8')

/** Generate `length` random bytes as a hex string. */
export function randomSecret(length = 32): string {
  return randomBytes(length).toString('hex')
}

function sign(secret: string, twinId: string, kind: TokenKind): string {
  return createHmac('sha256', secret).update(`${twinId}.${kind}`).digest('hex')
}

/**
 * Create a token string for a twin/kind.
 * The server secret must stay server-side; the token is what a twin holds.
 */
export function createToken(serverSecret: string, twinId: string, kind: TokenKind): string {
  return `${TOKEN_PREFIX}${twinId}.${kind}.${sign(serverSecret, twinId, kind)}`
}

/** Hash of a token used for at-rest storage (server only). */
export function hashToken(token: string): string {
  return createHmac('sha256', 'roster-token-hash').update(token).digest('hex')
}

/**
 * Verify a token against the server secret and expected kind.
 * Returns the parsed payload on success, or `undefined` on any mismatch.
 * Signature comparison is constant-time.
 */
export function verifyToken(
  serverSecret: string,
  token: string | undefined,
  kind: TokenKind,
): TokenPayload | undefined {
  if (!token || !token.startsWith(TOKEN_PREFIX)) return undefined
  const body = token.slice(TOKEN_PREFIX.length)
  const dot1 = body.indexOf('.')
  if (dot1 <= 0) return undefined
  const dot2 = body.indexOf('.', dot1 + 1)
  if (dot2 <= dot1 + 1) return undefined
  const twinId = body.slice(0, dot1)
  const tokenKind = body.slice(dot1 + 1, dot2)
  const sig = body.slice(dot2 + 1)
  if (tokenKind !== kind) return undefined
  const expected = sign(serverSecret, twinId, kind)
  const a = Buffer.from(sig, 'utf8')
  const b = Buffer.from(expected, 'utf8')
  if (a.length !== b.length || !timingSafeEqual(a, b)) return undefined
  return { twinId, kind }
}

/** Generate a fresh id for a work item (short, url-safe). */
export function newId(): string {
  return randomBytes(6).toString('base64url')
}
